import React, { useState, useMemo, useEffect } from "react";
import { Wrench, CheckCircle, MapPin, Receipt, ArrowRight, User, Calendar, DollarSign, Phone, Map as MapIcon } from "lucide-react";
import { Order, Customer, CatalogItem, AppSettings } from "../types";
import { Button } from "@/components/ui/button";
import POS from "./POS";
import { Card, CardContent } from "@/components/ui/card";
import { logout } from "../lib/supabase";
import { storage } from "../services/storage";
import { APIProvider, Map, AdvancedMarker, Pin } from "@vis.gl/react-google-maps";

const API_KEY =
  process.env.GOOGLE_MAPS_PLATFORM_KEY ||
  (import.meta as any).env?.VITE_GOOGLE_MAPS_PLATFORM_KEY ||
  (globalThis as any).GOOGLE_MAPS_PLATFORM_KEY ||
  '';

interface TechnicianMobileViewProps {
  user: any;
  urgentOrders: any[];
  orders: Order[];
  onUpdateOrderStatus: (id: string, status: string) => void;
  onUpdateUrgentOrder?: (order: any) => void;
  settings: AppSettings;
  catalog: CatalogItem[];
  customers: Customer[];
  onCompletePOS: (order: Order) => void;
  onAddCustomer: (c: Customer) => void;
}

export default function TechnicianMobileView({
  user,
  urgentOrders,
  orders,
  onUpdateOrderStatus,
  onUpdateUrgentOrder,
  settings,
  catalog,
  customers,
  onCompletePOS,
  onAddCustomer
}: TechnicianMobileViewProps) {
  const [view, setView] = useState<"tasks" | "pos" | "report">("tasks");
  const [reportTab, setReportTab] = useState<"invoices" | "tasks">("invoices");
  const [selectedTask, setSelectedTask] = useState<any>(null);

  const assignedTasks = urgentOrders.filter((o) => o.technicianName === user.name);
  const pendingTasks = assignedTasks.filter((o) => o.status !== "completed");
  const [techLocation, setTechLocation] = useState<{lat: number; lng: number} | null>(null);

  useEffect(() => {
    if (!navigator.geolocation) return;
    
    // Check if there are active tasks
    if (pendingTasks.length > 0) {
      const watchId = navigator.geolocation.watchPosition(
        (position) => {
          const loc = { lat: position.coords.latitude, lng: position.coords.longitude };
          setTechLocation(loc);
          storage.saveTechLocation(user.name, loc);
        },
        (error) => {
          console.error("Error watching location:", error);
        },
        { enableHighAccuracy: true, maximumAge: 10000, timeout: 5000 }
      );
      
      return () => navigator.geolocation.clearWatch(watchId);
    }
  }, [pendingTasks.length, user.name]);

  const dailyReport = useMemo(() => {
    const today = new Date().toISOString().split('T')[0];
    
    // Invoices generated by this technician today
    const todaysInvoices = orders.filter(o => 
      o.technicianName === user.name && 
      new Date(o.date).toISOString().split('T')[0] === today
    );

    // Tasks completed by this technician today
    const todaysTasks = assignedTasks.filter(o => 
      o.status === "completed" && 
      new Date(o.date).toISOString().split('T')[0] === today // assuming date or completion date
    );

    const totalAmount = todaysInvoices.reduce((sum, inv) => sum + inv.grandTotal, 0);

    return {
      invoices: todaysInvoices,
      tasks: todaysTasks,
      totalAmount
    };
  }, [orders, assignedTasks, user.name]);

  const handleCompleteTaskClick = (task: any) => {
    setSelectedTask(task);
    setView("pos");
  };

  const handlePOSComplete = (order: Order) => {
    order.technicianName = user.name;
    onCompletePOS(order);
    if (selectedTask) {
      onUpdateOrderStatus(selectedTask.id, "completed");
    }
    setView("tasks");
    setSelectedTask(null);
  };

  const perms = user.permissions || {
    canLogin: true, canAcceptTask: true, canCompleteTask: true, canInvoice: true
  };

  if (view === "pos" && perms.canInvoice !== false) {
    return (
      <div className="absolute inset-0 bg-[#0c101b] z-50 overflow-y-auto">
        <div className="p-4 flex items-center justify-between border-b border-white/10 bg-black/40">
          <Button variant="ghost" onClick={() => setView("tasks")} className="text-white">
            <ArrowRight className="h-5 w-5 ml-2" />
            رجوع
          </Button>
          <h2 className="font-bold">فاتورة مهمة: {selectedTask?.id || "مبيعات"}</h2>
          <div />
        </div>
        <div className="p-4">
          <POS
            settings={{ ...settings, currentTechnician: user.name }} // Inject technician or handle context
            catalog={catalog}
            customers={customers}
            onComplete={handlePOSComplete}
            onAddCustomer={onAddCustomer}
            initialServiceOrder={selectedTask ? {
               id: selectedTask.id,
               customerId: selectedTask.customerId,
               customerName: selectedTask.customerName,
               expectedAmount: selectedTask.expectedAmount || 0,
               technicianName: user.name
            } : null}
            onClearInitialServiceOrder={() => setSelectedTask(null)}
          />
        </div>
      </div>
    );
  }

  if (view === "report") {
    return (
      <div className="min-h-screen bg-[#0c101b] text-white p-4 font-['Inter',sans-serif] md:max-w-md md:mx-auto border-x border-white/10 relative">
        <div className="flex items-center mb-6">
          <Button variant="ghost" onClick={() => setView("tasks")} className="text-white p-0 mr-[-8px]">
            <ArrowRight className="h-6 w-6 ml-2" />
          </Button>
          <h1 className="text-xl font-bold flex items-center gap-2">
            <Calendar className="h-5 w-5 text-blue-500" />
            تقرير اليومية
          </h1>
        </div>

        <Card className="bg-white/5 border-white/10 mb-6 relative overflow-hidden">
          <div className="absolute top-0 right-0 w-32 h-32 bg-blue-500/20 rounded-full blur-3xl"></div>
          <CardContent className="p-6 text-center relative z-10">
            <div className="text-sm text-white/70 mb-1">إجمالي تحصيلات اليوم</div>
            <div className="text-4xl font-bold text-white mb-2">{dailyReport.totalAmount.toLocaleString()} <span className="text-sm font-normal text-white/50">{settings.currency || "ر.س"}</span></div>
            <div className="flex justify-center gap-4 mt-4 pt-4 border-t border-white/10">
              <div>
                <div className="text-green-400 font-bold text-lg">{dailyReport.invoices.length}</div>
                <div className="text-xs text-white/60">الفواتير</div>
              </div>
              <div className="w-px bg-white/10"></div>
              <div>
                <div className="text-blue-400 font-bold text-lg">{dailyReport.tasks.length}</div>
                <div className="text-xs text-white/60">المهام المنجزة</div>
              </div>
            </div>
          </CardContent>
        </Card>

        <div className="flex gap-2 mb-4 bg-white/5 p-1 rounded-lg border border-white/10">
          <button 
            className={`flex-1 py-2 text-sm font-bold rounded-md transition-colors ${reportTab === "invoices" ? 'bg-blue-500/20 text-blue-400' : 'text-white/60 hover:text-white'}`}
            onClick={() => setReportTab("invoices")}
          >
            الفواتير ({dailyReport.invoices.length})
          </button>
          <button 
            className={`flex-1 py-2 text-sm font-bold rounded-md transition-colors ${reportTab === "tasks" ? 'bg-blue-500/20 text-blue-400' : 'text-white/60 hover:text-white'}`}
            onClick={() => setReportTab("tasks")}
          >
            المهام المنجزة ({dailyReport.tasks.length})
          </button>
        </div>

        <div className="space-y-3">
          {reportTab === "invoices" ? (
            dailyReport.invoices.length === 0 ? (
              <div className="text-center p-4 bg-white/5 rounded-lg border border-white/10 text-white/50 text-sm">
                لا توجد فواتير اليوم
              </div>
            ) : (
              dailyReport.invoices.map((inv) => (
                <div key={inv.id} className="bg-white/5 border border-white/10 rounded-lg p-3 flex justify-between items-center">
                  <div>
                    <div className="font-bold text-sm">{inv.customerName || "عميل نقدي"}</div>
                    <div className="text-xs text-white/50">فاتورة #{inv.id}</div>
                  </div>
                  <div className="font-bold text-green-400">
                    {inv.grandTotal.toLocaleString()} {settings.currency || "ر.س"}
                  </div>
                </div>
              ))
            )
          ) : (
            dailyReport.tasks.length === 0 ? (
              <div className="text-center p-4 bg-white/5 rounded-lg border border-white/10 text-white/50 text-sm">
                لا توجد مهام منجزة اليوم
              </div>
            ) : (
              dailyReport.tasks.map((task) => (
                <div key={task.id} className="bg-white/5 border border-green-500/30 rounded-lg p-3 flex justify-between items-center relative overflow-hidden">
                  <div className="absolute top-0 right-0 h-full w-1 border-r-4 border-green-500"></div>
                  <div>
                    <div className="font-bold text-sm pr-2">{task.customerName}</div>
                    <div className="text-xs text-white/50 pr-2 overflow-hidden text-ellipsis whitespace-nowrap max-w-[150px]">مهمة #{task.id} • {task.issue}</div>
                  </div>
                  <div className="text-xs px-2 py-1 bg-green-500/20 text-green-400 rounded">
                    مكتملة
                  </div>
                </div>
              ))
            )
          )}
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-[#0c101b] text-white p-4 font-['Inter',sans-serif] md:max-w-md md:mx-auto border-x border-white/10 relative">
      <div className="flex justify-between items-center mb-6">
        <div>
          <h1 className="text-xl font-bold flex items-center gap-2">
            <Wrench className="h-5 w-5 text-orange-500" />
            بوابة الفنيين
          </h1>
          <p className="text-white/60 text-sm">أهلاً بك، {user.name}</p>
        </div>
        <Button variant="outline" className="border-red-500/50 text-red-400 hover:bg-red-500/10" onClick={async () => {
          if(confirm("تسجيل الخروج؟")){
             await logout();
             localStorage.removeItem("crm_active_user");
             window.location.reload();
          }
        }}>
          خروج
        </Button>
      </div>

      <div className="grid grid-cols-3 gap-2 mb-6">
        <Card className="bg-white/5 border-white/10">
          <CardContent className="p-3 text-center flex flex-col items-center justify-center">
            <div className="text-xl font-bold text-orange-400">{pendingTasks.length}</div>
            <div className="text-[10px] text-white/60">مهام معلقة</div>
          </CardContent>
        </Card>
        <Card className="bg-white/5 border-white/10 cursor-pointer hover:bg-white/10 transition-colors" onClick={() => setView("report")}>
          <CardContent className="p-3 text-center flex flex-col items-center justify-center">
            <DollarSign className="h-5 w-5 text-blue-400 mb-1" />
            <div className="text-[10px] font-bold">يوميتي</div>
          </CardContent>
        </Card>
        {perms.canInvoice !== false && (
          <Card className="bg-white/5 border-white/10 cursor-pointer hover:bg-white/10 transition-colors" onClick={() => setView("pos")}>
            <CardContent className="p-3 text-center flex flex-col items-center justify-center">
              <Receipt className="h-5 w-5 mx-auto mb-1 text-green-400" />
              <div className="text-[10px] font-bold">فاتورة حرة</div>
            </CardContent>
          </Card>
        )}
      </div>

      <div className="space-y-4">
        {techLocation && pendingTasks.length > 0 && (
          <div className="mb-6">
            <h2 className="font-bold flex items-center gap-2 mb-3">
              <MapIcon className="h-4 w-4 text-blue-400" />
              موقعك الحالي (يتم مشاركته مع الإدارة)
            </h2>
            <div className="rounded-xl overflow-hidden border border-white/10 h-40 relative">
              {API_KEY ? (
                <APIProvider apiKey={API_KEY} version="weekly">
                  <Map
                    defaultCenter={techLocation}
                    defaultZoom={15}
                    mapId="DEMO_MAP_ID"
                    internalUsageAttributionIds={['gmp_mcp_codeassist_v1_aistudio']}
                    style={{ width: '100%', height: '100%' }}
                  >
                    <AdvancedMarker position={techLocation}>
                      <Pin background="#22c55e" glyphColor="#fff" />
                    </AdvancedMarker>
                  </Map>
                </APIProvider>
              ) : (
                <iframe 
                  width="100%" 
                  height="100%" 
                  frameBorder="0" 
                  style={{ border:0 }} 
                  src={`https://maps.google.com/maps?q=${techLocation.lat},${techLocation.lng}&hl=ar&z=15&output=embed`} 
                  title="موقع الفني المباشر"
                  allowFullScreen
                ></iframe>
              )}
              <div className="absolute top-2 right-2 bg-green-500 text-white text-[10px] px-2 py-1 rounded-full animate-pulse flex items-center gap-1 shadow-lg pointer-events-none">
                <div className="w-2 h-2 bg-white rounded-full"></div>
                تتبع نشط
              </div>
            </div>
          </div>
        )}

        <h2 className="font-bold flex items-center gap-2">
          مهامك الحالية
        </h2>
        {pendingTasks.length === 0 ? (
          <div className="text-center py-10 bg-white/5 rounded-xl border border-white/10">
            <CheckCircle className="h-10 w-10 text-green-500 mx-auto mb-2 opacity-50" />
            <p className="text-white/60">لا توجد مهام معلقة لك حالياً</p>
          </div>
        ) : (
          pendingTasks.map((task) => {
            const customer = customers.find(c => c.id === task.customerId);
            
            return (
              <Card key={task.id} className="bg-white/5 border-white/10 overflow-hidden">
                <div className={`h-1 w-full ${task.status === 'completed' ? 'bg-green-500' : task.status === 'in-progress' ? 'bg-blue-500' : 'bg-orange-500'}`}></div>
                <CardContent className="p-4">
                  <div className="flex justify-between items-start mb-2">
                    <h3 className="font-bold text-lg">{task.customerName}</h3>
                    <span className="text-xs bg-white/10 px-2 py-1 rounded">#{task.id}</span>
                  </div>
                  <p className="text-white/70 text-sm mb-4">{task.issue}</p>
                  
                  {customer?.phone && (
                    <div className="flex justify-between items-center bg-white/5 border border-white/10 rounded-lg p-2 mb-3">
                      <Button 
                        variant="ghost" 
                        size="sm"
                        className="bg-green-500/10 text-green-400 hover:bg-green-500/20 hover:text-green-300 border border-green-500/20"
                        onClick={() => {
                          window.location.href = `tel:${customer.phone}`;
                          if (task.contactStatus !== "success") {
                            const newLog = { date: Date.now(), text: "محاولة اتصال بالعميل" };
                            onUpdateUrgentOrder?.({
                              ...task, 
                              contactStatus: "attempted",
                              activityLogs: [...(task.activityLogs || []), newLog]
                            });
                          }
                        }}
                      >
                        <Phone className="h-4 w-4 ml-2" />
                        اتصال بالعميل
                      </Button>
                      <div className="flex items-center gap-1 text-xs">
                        <span className="text-white/50 ml-2">حالة الرد:</span>
                        <button
                          title="تم الرد والاستجابة"
                          onClick={() => {
                            const newLog = { date: Date.now(), text: "تم التواصل مع العميل بنجاح" };
                            onUpdateUrgentOrder?.({
                              ...task, 
                              contactStatus: "success",
                              activityLogs: [...(task.activityLogs || []), newLog]
                            });
                          }}
                          className={`px-2 py-1 rounded transition-colors ${task.contactStatus === 'success' ? 'bg-green-500 text-white' : 'bg-white/10 text-white/50 hover:bg-white/20'}`}
                        >
                          تم الرد
                        </button>
                        <button
                          title="لم يتم الرد"
                          onClick={() => {
                            const newLog = { date: Date.now(), text: "لم يتم الرد على الاتصال" };
                            onUpdateUrgentOrder?.({
                              ...task, 
                              contactStatus: "attempted",
                              activityLogs: [...(task.activityLogs || []), newLog]
                            });
                          }}
                          className={`px-2 py-1 rounded transition-colors ${task.contactStatus === 'attempted' ? 'bg-yellow-500 text-white' : 'bg-white/10 text-white/50 hover:bg-white/20'}`}
                        >
                          لم يرد
                        </button>
                      </div>
                    </div>
                  )}

                  <div className="flex gap-2">
                    <Button 
                      variant="outline" 
                      className="flex-1 border-white/10 bg-white/5"
                      onClick={() => {
                          window.open(`https://maps.google.com/?q=${task.locationId}`, "_blank");
                      }}
                    >
                      <MapPin className="h-4 w-4 ml-2 text-blue-400" />
                      الموقع
                    </Button>
                    
                    {task.status !== 'completed' && perms.canCompleteTask !== false && (
                      <Button 
                        className="flex-1 bg-green-600 hover:bg-green-500"
                        onClick={() => handleCompleteTaskClick(task)}
                      >
                        <CheckCircle className="h-4 w-4 ml-2" />
                        إتمام
                      </Button>
                    )}
                  </div>
                </CardContent>
              </Card>
            );
          })
        )}
      </div>
    </div>
  );
}
